### ISSUE TITLE
Unable to fun new nodes

### ISSUE THREAD

**Issue by ScriptedAlchemy** [thegreatdb/siacdn#2]
I love your work here! But am gaving some challanges getting it running.

Once i create an account, add a node and wait for it to do its thing, it always gets stuck at step 9, waiting for confirmation of funds. Ive left it for over 12 hours my main wallet never shows any transactions (confirmed or not) going to the new node wallet that was setup 

I think it might be related to the source wallet not unlocking?

![image](https://user-images.githubusercontent.com/25274700/35489852-d5f9a520-0468-11e8-8679-6ce1262eeddf.png)

**Comment by ericflo** [comment]
Closing because SiaCDN has changed significantly since its inception. Sorry for any trouble!
